def countryList():
	colist = ['Angola',
	'Benin',
	'Botswana',
	'Burkina Faso',
	'Burundi',
	'Cameroon',
	'Cape Verde',
	'Central African Republic',
	'Chad',
	'Comoros',
	'Congo (Brazzaville)',
	'Congo (Democratic Republic)',
	"CC4te d'Ivoire",
	'Djibouti',
	'Equatorial Guinea',
	'Eritrea',
	'Ethiopia',
	'Gabon',
	'The Gambia',
	'Ghana',
	'Guinea',
	'Guinea-Bissau',
	'Kenya',
	'Lesotho',
	'Liberia',
	'Madagascar',
	'Malawi',
	'Mali',
	'Mauritania',
	'Mauritius',
	'Mozambique',
	'Namibia',
	'Niger',
	'Nigeria',
	'RC)union',
	'Rwanda',
	'Sao Tome and Principe',
	'Senegal',
	'Seychelles',
	'Sierra Leone',
	'Somalia',
	'South Africa',
	'Sudan',
	'Swaziland',
	'Tanzania',
	'Togo',
	'Uganda',
	'Western Sahara',
	'Zambia',
	'Zimbabwe']
	return colist