def countryList():
	colist = ['Angola',
	'Benin',
	'Botswana',
	'Burkina Faso',
	'Burundi',
	'Cameroon',
	#'Cape Verde', #cabo verde
	'Central African Republic',
	'Chad',
	'Comoros',
	#'Congo (Brazzaville)',
	#'Congo (Democratic Republic)', #parens? #congo, rep.
	#"CC4te d'Ivoire",
	'Djibouti',
	'Equatorial Guinea',
	'Eritrea',
	'Ethiopia',
	'Gabon',
	#'The Gambia', #gambia, the
	'Ghana',
	'Guinea',
	'Guinea-Bissau',
	'Kenya',
	'Lesotho',
	'Liberia',
	'Madagascar',
	'Malawi',
	'Mali',
	'Mauritania',
	'Mauritius',
	'Mozambique',
	'Namibia',
	'Niger',
	'Nigeria',
	##'RC)union',
	'Rwanda',
	'Sao Tome and Principe',
	'Senegal',
	'Seychelles',
	'Sierra Leone',
	'Somalia',
	'South Africa',
	'Sudan',
	'Swaziland',
	'Tanzania',
	'Togo',
	'Uganda',
	#'Western Sahara',
	'Zambia',
	'Zimbabwe']
	return colist

if __name__=="__main__":
	print countryList()